### ISSUE TITLE
Mission page button on permalinked posts categorized as "new" is broken

### ISSUE THREAD

**Issue by jakehlee** [columbiaspace/columbiaspace.org#58]
Probably an issue because I automated everything, didn't expect news that isn't mission-related

Solution would be to make the button go directly to the news page instead of a missions page. If/else statement should take care of it.

Let me eat dinner first.

Example link: 
https://columbiaspace.org/news/2015/12/18/news-star-wars-trip/

**Comment by jakehlee** [comment]
Read the title and thought, "well that doesn't make any sense"

**Comment by jakehlee** [comment]
Status: probably getting rid of the news posts altogether, replacing it with a full social media feed.

**Comment by jakebox** [comment]
I see the issue, sort of.

<img width="538" alt="image" src="https://github.com/columbiaspace/columbiaspace.org/assets/26366643/5eacce89-25b0-4d0b-b9e9-a7df367487e0">

Should link to columbiaspace.org/news, rather than something like http://www.columbiaspace.org/mission-microbio.

Or it can link to the overall news page to return back.

I think that either one is fine. Need to decide or get input.

**Comment by jakehlee** [comment]
Closed by @hibaa8 with 29eb274
